version: "3.5"

services:
  sonarqube:
    image: sonarqube:7.9-community
    ports:
      - "9000:9999"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_HOME=/opt/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./app/sonarqube/conf:/opt/sonarqube/conf
      - ./app/sonarqube/data:/opt/sonarqube/data
      - ./app/sonarqube/logs:/opt/sonarqube/logs
      - ./app/sonarqube/extensions:/opt/sonarqube/extensions
    restart: unless-stopped

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./app/sonarqube/postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  sonarnet:
    driver: bridge
