version: 2
jobs:
  build:

    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8u171-jdk-stretch-browsers

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:

      # Step 1: obtain repo from GitHub
      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "ewpsp/pom.xml" }}-{{ checksum "ewp-api-agent/pom.xml" }}-{{ checksum "energyServicePortal_ewp_adv/pom.xml" }}

      - run: mvn -f energyServicePortal_ewp_adv/pom.xml dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "ewpsp/pom.xml" }}-{{ checksum "ewp-api-agent/pom.xml" }}-{{ checksum "energyServicePortal_ewp_adv/pom.xml" }}

      # run tests!
      # run: mvn integration-test
      #- run:
      #    name: static code analysis
      #    command: |
      #      mv settings.xml ~/.m2/settings.xml
      #      mvn -f ewpsp/pom.xml clean package sonar:sonar
      #      mvn -f ewp-api-agent/pom.xml clean package sonar:sonar
      #      mvn -f energyServicePortal_ewp_adv/pom.xml clean package sonar:sonar

      - run: mvn -f energyServicePortal_ewp_adv/pom.xml clean package -DskipTests=true

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Move build files from target directory to root
          command: |
            cp ewpsp/target/ewpsp.war .
            cp ewp-api-agent/target/ewp-api-0.0.1-SNAPSHOT.jar .
            cp energyServicePortal_ewp_adv/target/energyServicePortal-1.0.0.war .

      - store_artifacts:
          path: ewpsp/target/ewpsp.war

      - store_artifacts:
          path: ewp-api-agent/target/ewp-api-0.0.1-SNAPSHOT.jar

      - store_artifacts:
          path: energyServicePortal_ewp_adv/target/energyServicePortal-1.0.0.war

      - store_artifacts:
          path: scripts/deploy.sh

      - store_artifacts:
          path: scripts/health-check.sh

      - store_artifacts:
          path: sitespeed.io/login.js

      - persist_to_workspace:
          root: ~/circleci-demo-java-spring
          paths:
            - ewpsp.war
            - ewp-api-0.0.1-SNAPSHOT.jar
            - energyServicePortal-1.0.0.war
            - scripts/deploy.sh
            - scripts/health-check.sh
            - sitespeed.io/login.js

  deploy:
    docker:
      - image: circleci/openjdk:8u171-jdk-stretch-browsers
    steps:
      - attach_workspace:
          at: ~/circleci-demo-java-spring
      - run:
          name: Generate ssh key
          command: |
            mkdir ~/.ssh
            chmod 700 ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            if [ "$CIRCLE_BRANCH" = "khnp" ] || [ "$CIRCLE_BRANCH" = "iDERMS-SaaS" ]; then
              echo -e "id_rsa file is created in $CIRCLE_BRANCH branch"
              echo -e $SSH_PRIVATE_KEY_KHNP > ~/.ssh/id_rsa
            else
              echo -e $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
            fi
            chmod 600 ~/.ssh/id_rsa
      - run:
          name: Build and push SP Docker image (jar)
          command: |
            if [ "$CIRCLE_BRANCH" = "khnp" ]; then
              REMOTE_SERVER=$SSH_USER@$SSH_HOST_KHNP
              scp ~/circleci-demo-java-spring/ewpsp.war $REMOTE_SERVER:/home/ubuntu/build
              scp ~/circleci-demo-java-spring/ewp-api-0.0.1-SNAPSHOT.jar $REMOTE_SERVER:/home/ubuntu/build
              scp ~/circleci-demo-java-spring/scripts/*.sh $REMOTE_SERVER:/home/ubuntu/
              ssh $REMOTE_SERVER 'chmod 755 ./deploy.sh; ./deploy.sh; chmod 755 ./health-check.sh; ./health-check.sh'
            elif [ "$CIRCLE_BRANCH" = "iDERMS-SaaS" ]; then
              echo -e "build in iDERMS-SaaS"
              REMOTE_SERVER=$SSH_USER_SAAS@$SSH_HOST_SAAS
              scp ~/circleci-demo-java-spring/energyServicePortal-1.0.0.war $REMOTE_SERVER:/usr/local/apache-tomcat-9.0.31/webapps
              scp ~/circleci-demo-java-spring/scripts/*.sh $REMOTE_SERVER:/home/ec2-user/
              ssh $REMOTE_SERVER 'chmod 755 ./deploy.sh; ./deploy.sh; chmod 755 ./health-check.sh; ./health-check.sh'
            else
              REMOTE_SERVER=$SSH_USER@$SSH_HOST
              scp -i ~/.ssh/ewp.pem -o StrictHostKeyChecking=no ~/circleci-demo-java-spring/ewpsp.war $REMOTE_SERVER:/home/ubuntu/build
              scp -i ~/.ssh/ewp.pem -o StrictHostKeyChecking=no ~/circleci-demo-java-spring/ewp-api-0.0.1-SNAPSHOT.jar $REMOTE_SERVER:/home/ubuntu/build
              scp -i ~/.ssh/ewp.pem -o StrictHostKeyChecking=no ~/circleci-demo-java-spring/scripts/*.sh $SSH_USER@$SSH_HOST:/home/ubuntu/
              ssh -i ~/.ssh/ewp.pem -o StrictHostKeyChecking=no $REMOTE_SERVER 'chmod 755 ./deploy.sh; ./deploy.sh;'
            fi

  test-sitespeed:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Initial setting"
          command: |
            sudo modprobe ifb numifbs=1
      - run:
          name: "Run test"
          command: |
            docker run --rm -v $(pwd)/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io:8.14.0 --preScript /sitespeed.io/login.js http://derms.enertalk.com:8080/main
      - store_artifacts:
          path: sitespeed.io/sitespeed-result/

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/circleci-demo-java-spring
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=1.1.2
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /root/circleci-demo-java-spring

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - khnp
                - iDERMS-SaaS
      - test-sitespeed:
          requires:
            - build
          filters:
            branches:
              only: master
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only: master
